name: Test build on Windows nightly
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - .github/workflows/build-on-windows-nightly.yml
  schedule:
    - cron: "37 19 * * *"
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: windows-latest
    concurrency:
      group: build-on-windows-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: pwd
        run: pwd
      - name: ls
        run: ls -la
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Create React Native App
        run: npx react-native init App
      - name: Setup Yarn
        working-directory: App
        run: yarn set version 4.1.1 --yarn-path
      - name: Setup Yarn lockfile
        working-directory: App
        run: touch yarn.lock
      - name: Echo yarn version
        working-directory: App
        run: yarn --version
      - name: Install dependencies
        working-directory: App
        run: yarn install
      - name: Install Reanimated
        working-directory: App
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Build Android App
        working-directory: App/android
        run: ./gradlew assembleDebug --console=plain
