name: Check Expo dev-client nightly build
on:
  pull_request:
    paths:
      - .github/workflows/check-expo-dev-client-nightly.yml
  schedule:
    - cron: '0 0 * * *' # after publishing new nightly version on NPM
  workflow_dispatch:

jobs:
  check-expo-dev-client-next-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Check Expo dev-client next availability
        run: npm dist-tag ls expo-dev-client | grep next
        id: check-next-availability
      - name: Run next build
        if: steps.check-next-availability.outcome == 'success'
        uses: ./.github/workflows/check-expo-dev-client-action.yml
        with:
          expo_dev_client_version: next
      - name: Run latest build
        uses: ./.github/workflows/check-expo-dev-client-action.yml
        with:
          expo_dev_client_version: latest
